spring:
  application:
    name: secure-auth

  datasource:
    url: jdbc:postgresql://localhost:5432/secure_auth
    username: postgres
    password: 1234567Steven..,
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # Flyway handles schema
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: localhost
    port: 6379

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 465
    username: ekehsteven2@gmail.com
    password: gzbs oooi akch phbv
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true   # since you are using port 465 (SSL)
          starttls:
            enable: true   # if using 587 instead of 465

server:
  port: 8080

jwt:
  secret: "v2DQ/qdsoALW2JjL8a86ENcoBIE1QWAm2sIn10LJa1U="
  expiration-ms: 3600000 # 1 hour in milliseconds

file:
  upload-dir: ./uploads/profile-pictures

debug: true

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    com.steve.secure_auth: DEBUG
